### ISSUE TITLE
Problem with encoding in nginx guide for domain aliases

### ISSUE THREAD

**Issue by redstrate** [jippi/masto-guide#6]
Thank you for the great guide on setting up webfinger redirection! While testing it on my site, I encountered a peculiar issue regarding the encoding you suggest (turning @ into %040 and whatnot) and for some reason it didn't work in my case. To actually make it function on my server, I just simply typed in `@redstrate@mastodon.art` without manually encoding it and then the redirect worked.

I wonder if something changed in recent nginx versions? This is what nginx reports on my machine:

```
nginx version: nginx/1.23.2
```

If I find the root cause of it, I'll be sure to open a PR to add a separate guide step for nginx versions above whatever number.

**Comment by jippi** [comment]
Thank you! :) 

I fixed this now so it doesn't need the encoding, seems like it might have changed over time :)
